[package]
name = "t0x-macros"
version = "0.1.5"
edition = "2024"
license = "MIT"
repository = "https://github.com/taskylizard/t0x"
description = "Derive macros for t0x"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "parsing", "extra-traits"] }
