[package]
name = "t0x"
version = "0.1.7"
edition = "2024"
license = "MIT"
repository = "https://github.com/taskylizard/t0x"
description = "Generate TypeScript types from Rust types using oxc"

[features]
default = []
serde-json-impl = ["serde_json"]

[dependencies]
oxc_allocator = "0.101"
oxc_ast = "0.101"
oxc_codegen = "0.101"
oxc_span = "0.101"
t0x-macros = { path = "../t0x-macros", version = "0.1.7" }

serde_json = { version = "1", optional = true }

[dev-dependencies]
